services:
  - type: web
    name: miappmvc
    env: docker
    dockerfilePath: ./dockerfile
    dockerContext: .
    plan: free
    buildCommand: ""
    startCommand: ""
    port: 80
    healthCheckPath: /
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/public
      - key: DATABASE_URL
        fromDatabase:
          name: miappmvc-db
          property: connectionString

databases:
  - name: miappmvc-db
    databaseName: db_personas
    user: miappmvc_user
    plan: free